### PR TITLE
Fix type definitions due to nulls

### PR DESCRIPTION
**Pull request by dalthon**
This PR fix return types of following functions for `Heap`, `MinHeap` and `MaxHeap` classes:

* `extractRoot()`
* `pop()`
* `root()`
* `top()`
* `leaf()`

Former definitions ignored the case of returning `null` when having an empty structure, but after this PR, type definitions will handle that.

### CODE REVIEW

**Comment by dalthon** [comment]
Hi @eyas-ranjous, first of all, this is a really nice package!

But I had an issue with eslint and your package when using it with typescript, and decided to help fixing it.

It raised `@typescript-eslint/no-unnecessary-condition` when I was checking the return of `root()` method like this:

```ts
    const node = heap.root()
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
    if (!node) return undefined
```

So I had to skip `no-unnecessary-condition` check because I know that it could be actually necessary.

This PR aims to fix that kind of type checking issues.

**Review by eyas-ranjous — APPROVED** [review]

**Comment by eyas-ranjous** [comment]
@dalthon thanks for making the change. fix is released v4.3.2

**Comment by k290** [comment]
@eyas-ranjous  @dalthon 

The design decision of returning `null` when the heap is empty combined with (correctly) typing it to reflect this, does make the library quite cumbersome now.

My codebase is now littered with nul-lchecks. Or casts from the `T?` I get out, back to the `T` I originally `push`ed in when I'm writing code that will never pop on an empty heap.

I mean I'll cope but it is annoying and adds lots of superfluous code to my implementation.  

But that said this PR is correct and I would not necessarily suggest it be reverted.

For consideration, many other implementations in other languages throw exceptions when popping, getting leafs etc from an empty heap, rather than altering the datatype that was originally passed into the heap to a nullable version that comes out.

**Comment by eyas-ranjous** [comment]
I don't think that throwing an exception for an empty heap or any datastructure is a better idea. You will have to wrap with try/catch everywhere and trying to pop elements despite that not being an error triggering operation.

Null value represents the absence of any value which is true for data structures. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/null 

When popping a value from the heap, you have the size (and isEmpty) functions to check if there are elements when trying to pop elements. when an element exist in the heap, size is bigger than 1 and isEmpty is false

**Comment by dalthon** [comment]
@k290 for good or bad, that's exactly the point of type checking: making sure that you will have to think about possible changes in your code due to unexpected types being passed forward.

I would expect a library like this to assume general use, so if it is possible to try to pop from an empty heap this should be handled somehow, either by returning null or raising an error.

If in your particular use, you expect to never pop from an empty heap and thus never falls on this case, then you maybe should wrap this data structure and raise an error.

**Pull request merged**
